**

diff --git a/resources/scripts/nepi_ai_test b/resources/scripts/nepi_ai_test
--- a/resources/scripts/nepi_ai_test
+++ b/resources/scripts/nepi_ai_test
@@ -13,10 +13,10 @@
 # Run and AI Detection Speed test
 
 
-if ! [ $(id -u) = 0 ]; then
-   echo 'This scripts must be run as root user. Type "sudo su" and retry'
-   exit 1
-fi
+# if ! [ $(id -u) = 0 ]; then
+#    echo 'This scripts must be run as root user. Type "sudo su" and retry'
+#    exit 1
+# fi
 
 
 SCRIPT_FOLDER=$(cd -P "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
