*0*

diff --git a/resources/bash/foo b/resources/bash/foo
--- a/resources/bash/foo
+++ b/resources/bash/foo
@@ -4341,7 +4341,6 @@ fi
 WHITE='\033[0;37m'
 GREEN='\033[0;32m'
 YELLOW='\033[33m'
-ORANGE='\033[0;33m'
 RED='\033[0;31m'
 
 alias nepihome="
@@ -5344,20 +5343,124 @@ function gitmain {
 
 
 function pushr(){
-
-  do_checks=$1
-  if [[ -z $do_checks ]]; then
-    do_checks=1
-  fi
-
-
-  echo -e "${WHITE}Pushing repo ${PWD##*/}"
-
   cur_path=$(pwd)
   cur_folder=${PWD##*/}
 
+  if ! is_valid_internet >/dev/null 2>&1; then
+    echo -e "${RED}Internet Not Connected"
+    echo -e "${WHITE}"
+    return 1
+  fi
 
-  if [[ $do_checks -eq 1 ]]; then
+  head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+  if [ "$?" -gt 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+    echo -e "${RED}Not a Git Repo $(pwd)"
+    echo -e "${WHITE}"
+    return 1
+  fi
+
+  ssh -T git@github.com >/dev/null 2>&1
+  if [[ "$?" -gt 1 ]]; then
+    echo -e "${RED}Git SSH Credentials Failed"
+    echo -e "${WHITE}"
+    return 1
+  fi
+
+
+
+  #echo -e "${GREEN}Clearing __pycache__ folders"
+  echo -e "${WHITE}Pushing to repo ${PWD##*/}"
+  echo -e "${WHITE}#######################"
+
+
+
+  git add --all >/dev/null 2>&1
+  git commit -m "*$@*" >/dev/null 2>&1
+
+  if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then   
+      git checkout develop
+  else
+      git checkout  main
+      #git checkout main
+  fi
+
+
+  # git push --dry-run >/dev/null 2>&1
+  # if [[ ! $? -eq 0 ]]; then
+  #   echo -e "${RED}Push Failed: You Don't have Push Credentials $(pwd)"
+  #   echo -e "${WHITE}"
+  #   return 1
+  # fi
+
+  find ./ -type d -name "__pycache__" -exec sudo rm -rf {} +
+
+  git pull --no-edit
+  if [ $? -eq 0 ]; then
+    echo -e "${WHITE}Pushing Merged repo ${PWD##*/}"
+    git push origin HEAD:main
+    if [ ! $? -eq 0 ]; then
+      echo -e "${WHITE}#######################"
+      echo -e "${RED}Push Failed"
+      echo -e "${WHITE}"
+      return 1 # Failed
+    fi
+  fi
+
+
+  echo -e "${WHITE}#######################"
+  echo -e "${GREEN}Push Successfully"
+  echo -e "${WHITE}"
+}
+export -f pushr
+
+function pullr {
+  if ! is_valid_internet >/dev/null 2>&1; then
+    echo -e "${RED}Internet Not Connected"
+    echo -e "${WHITE}"
+    return 1
+  fi
+
+  head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+  if [[ "$?" -gt 0 ]]; then #$(is_git_repo $PWD) -eq 1 ]; then
+    echo -e "${RED}Not a Git Repo $(pwd)"
+    echo -e "${WHITE}"
+    return 1
+  fi
+
+  ssh -T git@github.com >/dev/null 2>&1
+  if [[ "$?" -gt 1 ]]; then
+    echo -e "${RED}Git SSH Credentials Failed"
+    echo -e "${WHITE}"
+    return 1
+  fi
+
+  if [ -n "$(git status --porcelain)" ]; then
+    git push --dry-run >/dev/null 2>&1
+    if [[ ! $? -eq 0 ]]; then
+      echo -e "${YELLOW}Pushing Uncommited Changes First"
+      echo -e "${WHITE}"
+      pushr
+    else
+      echo -e "${RED}Repo Has Uncommited Changes. Pull Failed"
+      echo -e "${WHITE}"
+      return 1
+    fi
+  else
+    git pull
+  fi
+
+  if [[ $? -eq 0 ]]; then
+    echo -e "${GREEN}Pull Successfull"
+    echo -e "${WHITE}"
+  else
+    echo -e "${RED}Pull Failed"
+    echo -e "${WHITE}"
+  fi
+   
+}
+export -f pullr
+
+function pullrc {
     if ! is_valid_internet >/dev/null 2>&1; then
       echo -e "${RED}Internet Not Connected"
       echo -e "${WHITE}"
@@ -5377,120 +5480,6 @@ function pushr(){
       echo -e "${WHITE}"
       return 1
     fi
-  fi
-
-
-
-  current_branch=$(git branch --show-current)
-  repo_status=$(git status --porcelain)
-  if [[ -n $repo_status || -z $current_branch ]]; then
-
-
-    git add --all >/dev/null 2>&1
-    git commit -m "*$@*" >/dev/null 2>&1
-
-
-    if git symbolic-ref -q HEAD >/dev/null; then
-        current_branch=$(git branch --show-current)
-    else
-        #echo "HEAD is DETACHED!"
-        if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then   
-            git checkout develop
-        else
-            git checkout main
-        fi
-        current_branch=$(git branch --show-current)
-    fi
-
-    if [[ -z $current_branch ]]; then
-      echo -e "${RED}Git Repo not on branch. Pull Failed"
-      echo -e "${WHITE}"
-      return 1
-    fi 
-
-
-    # git push --dry-run >/dev/null 2>&1
-    # if [[ ! $? -eq 0 ]]; then
-    #   echo -e "${RED}Push Failed: You Don't have Push Credentials $(pwd)"
-    #   echo -e "${WHITE}"
-    #   return 1
-    # fi
-
-    find ./ -type d -name "__pycache__" -exec sudo rm -rf {} +
-
-    echo -e "${YELLOW}Pushing Merged repo ${PWD##*/}"
-    echo -e "${WHITE}${repo_status}"
-    git push origin HEAD:$current_branch
-    if [ ! $? -eq 0 ]; then
-      if [[ $do_checks -eq 1 ]]; then
-        echo -e "${RED}Push Failed"
-        echo -e "${WHITE}"
-        return 2 # Failed
-      else
-        pullrc 0
-        return $?
-      fi
-    fi
-  fi
-  echo -e "${GREEN}Push Successfully"
-  echo -e "${WHITE}"
-
-}
-export -f pushr
-
-function pullrc {
-
-    echo -e "${WHITE}Pulling repo CLEAN ${PWD##*/}"
-
-    do_checks=$1
-    if [[ -z $do_checks ]]; then
-      do_checks=1
-    fi
-
-    cur_path=$(pwd)
-    cur_folder=${PWD##*/}
-
-
-    if [[ $do_checks -eq 1 ]]; then
-      if ! is_valid_internet >/dev/null 2>&1; then
-        echo -e "${RED}Internet Not Connected"
-        echo -e "${WHITE}"
-        return 1
-      fi
-
-      head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-      if [ "$?" -gt 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-        echo -e "${RED}Not a Git Repo $(pwd)"
-        echo -e "${WHITE}"
-        return 1
-      fi
-
-      ssh -T git@github.com >/dev/null 2>&1
-      if [[ "$?" -gt 1 ]]; then
-        echo -e "${RED}Git SSH Credentials Failed"
-        echo -e "${WHITE}"
-        return 1
-      fi
-    fi
-
-    current_branch=$(git branch --show-current)
-    if git symbolic-ref -q HEAD >/dev/null; then
-        current_branch=$(git branch --show-current)
-    else
-        #echo "HEAD is DETACHED!"
-        if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then   
-            git checkout develop
-        else
-            git checkout  main
-        fi
-        current_branch=$(git branch --show-current)
-    fi
-
-    if [[ -z $current_branch ]]; then
-      echo -e "${RED}Git Repo not on brach. Pull Failed"
-      echo -e "${WHITE}"
-      return 1
-    fi
 
     git fetch --all --prune
     git reset --hard @{upstream}
@@ -5501,94 +5490,15 @@ function pullrc {
     git submodule foreach --recursive 'git clean -ffdx'
 
     if [[ $? -eq 0 ]]; then
-      echo -e "${GREEN}Pull Clean Successfull"
+      echo -e "${GREEN}Pull Successfull"
+      echo -e "${WHITE}"
     else
-      echo -e "${RED}Pull Clean Failed"
-      return 1
+      echo -e "${RED}Pull Failed"
+      echo -e "${WHITE}"
     fi
 
 }
 export -f pullrc
-
-
-
-function pullr {
-
-    do_checks=$1
-    if [[ -z $do_checks ]]; then
-      do_checks=1
-    fi
-
-    echo -e "${WHITE}Pulling repo ${PWD##*/}"
-
-    cur_path=$(pwd)
-    cur_folder=${PWD##*/}
-
-
-    if [[ $do_checks -eq 1 ]]; then
-      if ! is_valid_internet >/dev/null 2>&1; then
-        echo -e "${RED}Internet Not Connected"
-        echo -e "${WHITE}"
-        return 1
-      fi
-
-      head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-      if [ "$?" -gt 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-        echo -e "${RED}Not a Git Repo $(pwd)"
-        echo -e "${WHITE}"
-        return 1
-      fi
-
-      ssh -T git@github.com >/dev/null 2>&1
-      if [[ "$?" -gt 1 ]]; then
-        echo -e "${RED}Git SSH Credentials Failed"
-        echo -e "${WHITE}"
-        return 1
-      fi
-    fi
-
-    current_branch=$(git branch --show-current)
-    if git symbolic-ref -q HEAD >/dev/null; then
-        current_branch=$(git branch --show-current)
-    else
-        #echo "HEAD is DETACHED!"
-        if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then   
-            git checkout develop
-        else
-            git checkout  main
-        fi
-        current_branch=$(git branch --show-current)
-    fi
-
-    if [[ -z $current_branch ]]; then
-      echo -e "${RED}Git Repo not on brach. Pull Failed"
-      echo -e "${WHITE}"
-      return 1
-    fi
-
-  if [ -n "$(git status --porcelain)" ]; then
-    echo -e "${ORANGE}Repo Has Uncommited Changes"
-    pushr 0 >/dev/null 2>&1
-    if [[ $? -eq 0 ]]; then
-      echo -e "${GREEN}Pushed Uncommited Changes"
-    else
-      echo -e "${RED}Pull Failed"
-      echo -e "${ORANGE} -- Call 'pullrc' to force pull of latest git repo"
-      return 1
-    fi
-  else
-    git pull
-  fi
-
-  if [[ $? -eq 0 ]]; then
-    echo -e "${GREEN}Pull Successfull"
-  else
-    echo -e "${RED}Pull Failed"
-    return 1
-  fi
-   
-}
-export -f pullr
 
 
 function pushn {
@@ -5607,48 +5517,39 @@ function pushn {
 
     repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
     setup_folder=/home/${CONFIG_USER}/nepi_setup
+    
+    success=0
     cd $repo_folder      
     if [[ $? -gt 0 ]]; then
       echo -e "${RED}NEPI Repo Folder not found at: ${repo_folder}"
       echo -e "${WHITE}"
       return 1
-    fi
+    else
 
-    success=1
-    cd "${repo_folder}/nepi_setup"
-    echo -e "${WHITE}#########"
-    pushr 0
-    if [[ $? -eq 0 ]]; then
-      shopt -s nullglob
-      for dir in "$repo_folder"/src/*/ ; do
-          #echo "Processing Repo: $dir"
-          cd $dir
-          echo -e "${WHITE}#########"
-          pushr 0
-          if [[ $? -ne 0 ]]; then
-            success=0
-            break
-          fi
-      done
-      if [[ $success -eq 1 ]]; then
+      cd "${repo_folder}/nepi_setup"
+      pushr
+      if [[ $? -eq 0 ]]; then
+        shopt -s nullglob
+        for dir in "$repo_folder"/src/*/ ; do
+            #echo "Processing Repo: $dir"
+            cd $dir
+            pushr
+        done
         cd $repo_folder
-        echo -e "${WHITE}#########"
-        pushr 0
-        if [[ $? -ne 0 ]]; then
-          success=0
+        pushr
+        if [[ $? -eq 0 ]]; then
+          success=1
+          ubrc >/dev/null 2>&1
         fi
       fi
     fi
-  
-    echo -e "${WHITE}#######################"
+
     if [[ $success -eq 1 ]]; then
-      ubrc >/dev/null 2>&1
-      echo -e "${GREEN}NEPI Push Successfull"
-      echo -e "${WHITE}
+      echo -e "${GREEN}NEPI Pull Successfull"
+      echo -e "${WHITE}"
     else
-      echo -e "${RED}NEPI Push Failed"
-      echo -e "${WHITE}
-      return 1
+      echo -e "${RED}NEPI Pull Failed"
+      echo -e "${WHITE}"
     fi
 
 }
@@ -5669,9 +5570,9 @@ function pulln {
       return 1
     fi
 
-
     repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
     setup_folder=/home/${CONFIG_USER}/nepi_setup
+
     cd $repo_folder      
     if [[ $? -gt 0 ]]; then
       echo -e "${RED}NEPI Repo Folder not found at: ${repo_folder}"
@@ -5679,33 +5580,25 @@ function pulln {
       return 1
     fi
 
-
-    success=1
+    success=0
     cd "${repo_folder}/nepi_setup"
-    echo -e "${WHITE}#########"
-    pullr 0
+    pullr
     if [[ $? -eq 0 ]]; then
       shopt -s nullglob
       for dir in "$repo_folder"/src/*/ ; do
           #echo "Processing Repo: $dir"
           cd $dir
-          echo -e "${WHITE}#########"
-          pullr 0
-          if [[ $? -ne 0 ]]; then
-            success=0
-            break
-          fi
+          pullr
       done
-      if [[ $success -eq 1 ]]; then
-        cd $repo_folder
-        echo -e "${WHITE}#########"
-        pullr 0
-        if [[ $? -ne 0 ]]; then
-          success=0
-        fi
+      cd $repo_folder
+      pullr
+
+      if [[ $? -eq 0 ]]; then
+        success=1
+        ubrc >/dev/null 2>&1
       fi
     fi
-  
+ 
 
       # git add --all >/dev/null 2>&1
       # git commit -m "*$@*" >/dev/null 2>&1
@@ -5720,16 +5613,14 @@ function pulln {
       #     pullrc
       # fi
           
-    echo -e "${WHITE}#######################"
+      
     if [[ $success -eq 1 ]]; then
       ubrc >/dev/null 2>&1
       echo -e "${GREEN}NEPI Pull Successfull"
       echo -e "${WHITE}"
     else
-      echo -e "${RED}Pull Failed"
-      echo -e "${ORANGE} -- Call 'pullnc' to force pull of latest nepi get repo"
+      echo -e "${RED}NEPI Pull Failed"
       echo -e "${WHITE}"
-      return 1
     fi
 
 }
@@ -5750,52 +5641,28 @@ function pullnc {
       return 1
     fi
 
-
     repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
     setup_folder=/home/${CONFIG_USER}/nepi_setup
+
     cd $repo_folder      
     if [[ $? -gt 0 ]]; then
       echo -e "${RED}NEPI Repo Folder not found at: ${repo_folder}"
       echo -e "${WHITE}"
       return 1
-    fi
-
-
-    success=1
-    cd "${repo_folder}/nepi_setup"
-    echo -e "${WHITE}#########"
-    pullrc 0
-    if [[ $? -eq 0 ]]; then
-      shopt -s nullglob
-      for dir in "$repo_folder"/src/*/ ; do
-          #echo "Processing Repo: $dir"
-          cd $dir
-          echo -e "${WHITE}#########"
-          pullrc 0
-          if [[ $? -ne 0 ]]; then
-            success=0
-            break
-          fi
-      done
-      if [[ $success -eq 1 ]]; then
-        cd $repo_folder
-        echo -e "${WHITE}#########"
-        pullrc 0
-        if [[ $? -ne 0 ]]; then
-          success=0
-        fi
-      fi
-    fi
-  
-    echo -e "${WHITE}#######################"
-    if [[ $success -eq 1 ]]; then
-      ubrc >/dev/null 2>&1
-      echo -e "${GREEN}NEPI Pull Clean Successfull"
-      echo -e "${WHITE}"
     else
-      echo -e "${RED}NEPI Pull Clean Failed"
-      echo -e "${WHITE}"
-      return 1
+
+
+      pullrc
+
+          
+      if [[ $? -eq 0 ]]; then
+        ubrc >/dev/null 2>&1
+        echo -e "${GREEN}NEPI Pull Successfull"
+        echo -e "${WHITE}"
+      else
+        echo -e "${RED}NEPI Pull Failed"
+        echo -e "${WHITE}"
+      fi
     fi
 
 }
