**

diff --git a/resources/bash/nepi_pc_aliases b/resources/bash/nepi_pc_aliases
--- a/resources/bash/nepi_pc_aliases
+++ b/resources/bash/nepi_pc_aliases
@@ -198,72 +198,6 @@ else
   : # Do Nothing
 fi
 
-###################################
-# NEPI DEV Util Functions
-###################################
-export SOURCE_FOLDER=/home/${CONFIG_USER}/nepi_engine_ws
-GREEN='\033[0;32m'
-RED='\033[0;31m'
-
-## NEPI deploy complete
-alias nepisetup="
-source ${SOURCE_FOLDER}/nepi_setup/scripts/dev_pc_setup.sh"
-
-## NEPI deploy complete
-alias nepidpl="
-cd $SOURCE_FOLDER
-source ./deploy_nepi_complete.sh"
-
-# NEPI deploy repos
-alias repodpl="
-cd $SOURCE_FOLDER
-source ./deploy_nepi_repos.sh"
-
-utilsn="${utilsn}
-### NEPI DEV UTIL FUNCTIONS
-nepidpl = deploy nepi complete
-repodpl = deploy specific repos"
-
-function pushn(){
-  git add --all
-  git commit -m "*$@*" 
-  git push >/dev/null 2>&1
-  cur_folder=${PWD##*/}
-  par_path=$(dirname "$(pwd)")
-  par_folder=$(basename "$par_path")
-  #echo $cur_folder
-  #echo $par_folder
-  head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-  if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-    if [[ "$cur_folder" == 'nepi_engine_ws' || "$(pwd)" == "/home/${CONFIG_USER}/nepi_engine_ws/src" ]]; then
-        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head develop"
-        git push origin HEAD:develop
-
-    else
-        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head main"
-        git push origin HEAD:main
-        #git checkout main
-    fi
-    if [ ! $? -eq 0 ]; then
-      echo -e "${RED}Push Failed"
-      return 1 # Failed
-    fi
-    echo -e "${GREEN}Push Successfully"
-  else
-    echo -e "${RED}Not in Git Repo"
-  fi
-}
-
-HELPN="${HELPN}
-################################
-### NEPI DEV UTIL FUNCTIONS
-################################
-nepisetup = Rerun the pc_dev_setup script
-nepidpl = Deploy nepi complete to nepi device
-repodpl = Deploy repos to nepi device
-pushn = Add,commit,push repo changes with provided comment"
-
-
 
 ###################################
 #NEPI folder shortcuts
@@ -439,6 +373,77 @@ dcfg = /mnt/nepi_config/docker_cfg
 fcfg = /mnt/nepi_config/factory_cfg
 scfg = /mnt/nepi_config/system_cfg
 ucfg = /mnt/nepi_storage/user_cfg"
+
+
+
+
+
+
+###################################
+# NEPI DEV Util Functions
+###################################
+export SOURCE_FOLDER=/home/${CONFIG_USER}/nepi_engine_ws
+GREEN='\033[0;32m'
+RED='\033[0;31m'
+
+## NEPI deploy complete
+alias nepisetup="
+source ${SOURCE_FOLDER}/nepi_setup/scripts/dev_pc_setup.sh"
+
+## NEPI deploy complete
+alias nepidpl="
+cd $SOURCE_FOLDER
+source ./deploy_nepi_complete.sh"
+
+# NEPI deploy repos
+alias repodpl="
+cd $SOURCE_FOLDER
+source ./deploy_nepi_repos.sh"
+
+utilsn="${utilsn}
+### NEPI DEV UTIL FUNCTIONS
+nepidpl = deploy nepi complete
+repodpl = deploy specific repos"
+
+function pushn(){
+  git add --all
+  git commit -m "*$@*" 
+  git push >/dev/null 2>&1
+  cur_folder=${PWD##*/}
+  par_path=$(dirname "$(pwd)")
+  par_folder=$(basename "$par_path")
+  #echo $cur_folder
+  #echo $par_folder
+  head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+  if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+    if [[ "$cur_folder" == 'nepi_engine_ws' || "$(pwd)" == "/home/${CONFIG_USER}/nepi_engine_ws/src" ]]; then
+        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head develop"
+        git push origin HEAD:develop
+
+    else
+        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head main"
+        git push origin HEAD:main
+        #git checkout main
+    fi
+    if [ ! $? -eq 0 ]; then
+      echo -e "${RED}Push Failed"
+      return 1 # Failed
+    fi
+    echo -e "${GREEN}Push Successfully"
+  else
+    echo -e "${RED}Not in Git Repo"
+  fi
+}
+
+HELPN="${HELPN}
+################################
+### NEPI DEV UTIL FUNCTIONS
+################################
+nepisetup = Rerun the pc_dev_setup script
+nepidpl = Deploy nepi complete to nepi device
+repodpl = Deploy repos to nepi device
+pushn = Add,commit,push repo changes with provided comment"
+
 
 
 if [[ -d "/home/${CONFIG_USER}/nepi_engine_ws/nepi_setup/scripts" ]]; then
