**

diff --git a/resources/bash/nepi_bash_utils b/resources/bash/nepi_bash_utils
--- a/resources/bash/nepi_bash_utils
+++ b/resources/bash/nepi_bash_utils
@@ -5400,190 +5400,255 @@ function pushr(){
   cur_path=$(pwd)
   cur_folder=${PWD##*/}
 
-  head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-  if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-    #echo -e "${GREEN}Clearing __pycache__ folders"
-    echo -e "${WHITE}#######################"
-    echo -e "${WHITE}Pushing to repo ${PWD##*/}"
-    git add --all >/dev/null 2>&1
-    git commit -m "*$@*"  >/dev/null 2>&1
-    find ./ -type d -name "__pycache__" -exec sudo rm -rf {} +
-    if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then   
-        git push origin HEAD:develop
-    else
-        git push origin HEAD:main
-        #git checkout main
-    fi
-    if [ ! $? -eq 0 ]; then
-      echo ""
-      git pull --no-edit
-      if [ $? -eq 0 ]; then
-        echo -e "${GREEN}Pushing Merged repo ${PWD##*/} Head main"
-        git push origin HEAD:main
-        if [ ! $? -eq 0 ]; then
-          echo -e "${RED}Push Failed"
-          return 1 # Failed
-        fi
-      fi
-
-    fi
-    echo -e "${GREEN}Push Successfully"
-  else
-    echo -e "${RED}Not in Git Repo"
+  if ! is_valid_internet >/dev/null 2>&1; then
+    echo -e "${RED}Internet Not Connected"
+    echo -e "${WHITE}"
+    return 1
   fi
+
+  head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+  if [ "$?" -gt 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+    echo -e "${RED}Not a Git Repo $(pwd)"
+    echo -e "${WHITE}"
+    return 1
+  fi
+
+  ssh -T git@github.com >/dev/null 2>&1
+  if [[ "$?" -gt 1 ]]; then
+    echo -e "${RED}Git SSH Credentials Failed"
+    echo -e "${WHITE}"
+    return 1
+  fi
+
+  git push --dry-run >/dev/null 2>&1
+  if [ ! $? -eq 0 ]; then
+    echo -e "${RED}Push Failed: You Don't have Push Credentials $(pwd)"
+    echo -e "${WHITE}"
+    return 1
+  fi
+
+  #echo -e "${GREEN}Clearing __pycache__ folders"
+  echo -e "${WHITE}#######################"
+  echo -e "${WHITE}Pushing to repo ${PWD##*/}"
+
+  git add --all >/dev/null 2>&1
+  git commit -m "*$@*"  >/dev/null 2>&1
+  find ./ -type d -name "__pycache__" -exec sudo rm -rf {} +
+  if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then   
+      git push origin HEAD:develop
+  else
+      git push origin HEAD:main
+      #git checkout main
+  fi
+  if [ ! $? -eq 0 ]; then
+    echo ""
+    git pull --no-edit
+    if [ $? -eq 0 ]; then
+      echo -e "${WHITE}Pushing Merged repo ${PWD##*/}"
+      git push origin HEAD:main
+      if [ ! $? -eq 0 ]; then
+        echo -e "${RED}Push Failed"
+        echo -e "${WHITE}"
+        return 1 # Failed
+      fi
+    fi
+
+  fi
+  echo -e "${GREEN}Push Successfully"
+  echo -e "${WHITE}"
 }
 export -f pushr
 
 function pullr {
-  if is_valid_internet ; then
-    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-    if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-      git pull
-    else
-      echo -e "${RED}Not in Git Repo"
-    fi
+  if ! is_valid_internet >/dev/null 2>&1; then
+    echo -e "${RED}Internet Not Connected"
+    echo -e "${WHITE}"
+    return 1
   fi
+
+  head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+  if [ "$?" -gt 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+    echo -e "${RED}Not a Git Repo $(pwd)"
+    echo -e "${WHITE}"
+    return 1
+  fi
+
+  ssh -T git@github.com >/dev/null 2>&1
+  if [[ "$?" -gt 1 ]]; then
+    echo -e "${RED}Git SSH Credentials Failed"
+    echo -e "${WHITE}"
+    return 1
+  fi
+  
+  git pull
+   
 }
 export -f pullr
 
 function pullrc {
-  if is_valid_internet ; then
-    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-    if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-      echo -e "${GREEN}Clearing __pycache__ folders"
-      find ./ -type d -name "__pycache__" -exec rm -rf {} +
-      git fetch --all --prune
-      git reset --hard @{upstream}
-      git submodule sync --recursive
-      git submodule update --init --force --recursive
-      git submodule foreach --recursive 'git fetch --all --prune; git reset --hard @{upstream} || git reset --hard HEAD'
-      git clean -ffdx
-      git submodule foreach --recursive 'git clean -ffdx'
-    else
-      echo -e "${RED}Not in Git Repo"
+    if ! is_valid_internet >/dev/null 2>&1; then
+      echo -e "${RED}Internet Not Connected"
+      echo -e "${WHITE}"
+      return 1
     fi
-  fi
+
+    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+    if [ "$?" -gt 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+      echo -e "${RED}Not a Git Repo $(pwd)"
+      echo -e "${WHITE}"
+      return 1
+    fi
+
+    ssh -T git@github.com >/dev/null 2>&1
+    if [[ "$?" -gt 1 ]]; then
+      echo -e "${RED}Git SSH Credentials Failed"
+      echo -e "${WHITE}"
+      return 1
+    fi
+
+    git fetch --all --prune
+    git reset --hard @{upstream}
+    git submodule sync --recursive
+    git submodule update --init --force --recursive
+    git submodule foreach --recursive 'git fetch --all --prune; git reset --hard @{upstream} || git reset --hard HEAD'
+    git clean -ffdx
+    git submodule foreach --recursive 'git clean -ffdx'
 }
 export -f pullrc
 
-# function pushn(){
-#   cur_path=$(pwd)
-#   cur_folder=${PWD##*/}
-
-#   git add --all
-#   git commit -m "*$@*" 
-#   git push >/dev/null 2>&1
-
-#   par_path=$(dirname "$(pwd)")
-#   par_folder=$(basename "$par_path")
-#   #echo $cur_folder
-#   #echo $par_folder
-#   head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-#   if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-#     echo -e "${GREEN}Clearing __pycache__ folders"
-#     find ./ -type d -name "__pycache__" -exec sudo rm -rf {} +
-#     if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
-#         echo -e "${GREEN}Pushing to repo ${PWD##*/} Head develop"
-#         git push origin HEAD:develop
-#     else
-#         echo -e "${GREEN}Pushing to repo ${PWD##*/} Head main"
-#         git push origin HEAD:main
-#         #git checkout main
-#     fi
-#     if [ ! $? -eq 0 ]; then
-#       echo -e "${RED}Push Failed"
-#       return 1 # Failed
-#     fi
-#     echo -e "${GREEN}Push Successfully"
-#   else
-#     echo -e "${RED}Not in Git Repo"
-#   fi
-# }
-# export -f pushn
-
 
 function pushn {
-  if is_valid_internet ; then
+    if ! is_valid_internet >/dev/null 2>&1; then
+      echo -e "${RED}Internet Not Connected"
+      echo -e "${WHITE}"
+      return 1
+    fi
 
-      repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
-      setup_folder=/home/${CONFIG_USER}/nepi_setup
-      ssh -T git@github.com >/dev/null 2>&1
-      if [[ "$?" -lt 2 ]]; then
-        cd $repo_folder
-        head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-        if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-          if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
+    ssh -T git@github.com >/dev/null 2>&1
+    if [[ "$?" -gt 1 ]]; then
+      echo -e "${RED}Git SSH Credentials Failed"
+      echo -e "${WHITE}"
+      return 1
+    fi
 
-              cd "${repo_folder}/nepi_setup"
-              pushr
-              shopt -s nullglob
-              for dir in "$repo_folder"/src/*/ ; do
-                  #echo "Processing Repo: $dir"
-                  cd $dir
-                  pushr
-              done
-              cd $repo_folder
-              pushr
-                
-          fi
-          ubrc >/dev/null 2>&1
-        fi
-        echo "Git SSH Credentials Failed"
-      fi
-  fi
+    git push --dry-run >/dev/null 2>&1
+    if [ ! $? -eq 0 ]; then
+      echo -e "${RED}Push Failed: You Don't have Push Credentials $(pwd)"
+      echo -e "${WHITE}"
+      return 1
+    fi
+
+    repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
+    setup_folder=/home/${CONFIG_USER}/nepi_setup
+
+    cd $repo_folder
+
+    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+    if [ "$?" -gt 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+      echo -e "${RED}Not a Git Repo $(pwd)"
+      echo -e "${WHITE}"
+      return 1
+    fi
+
+    cd "${repo_folder}/nepi_setup"
+    pushr
+    if [[ $? -eq 0 ]]; then
+      shopt -s nullglob
+      for dir in "$repo_folder"/src/*/ ; do
+          #echo "Processing Repo: $dir"
+          cd $dir
+          pushr
+      done
+      cd $repo_folder
+      pushr
+          
+      ubrc >/dev/null 2>&1
+
+    fi
+
+
 }
 export -f pushn
 
 
 
+
 function pulln {
-  if is_valid_internet ; then
+    if ! is_valid_internet >/dev/null 2>&1; then
+      echo -e "${RED}Internet Not Connected"
+      echo -e "${WHITE}"
+      return 1
+    fi
 
-      repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
-      setup_folder=/home/${CONFIG_USER}/nepi_setup
+    ssh -T git@github.com >/dev/null 2>&1
+    if [[ "$?" -gt 1 ]]; then
+      echo -e "${RED}Git SSH Credentials Failed"
+      echo -e "${WHITE}"
+      return 1
+    fi
 
-      cd $repo_folder
-      head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-      if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-        if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
-            ssh -T git@github.com >/dev/null 2>&1
-            if [[ "$?" -lt 2 ]]; then
-                git pull --recurse-submodules
-                git submodule foreach --recursive "git checkout main && git push && git pull origin main" 2> /dev/null
-                #git submodule foreach --recursive "git add --all && git commit -m "*$@*" &&  git push && git checkout main && git push && git pull origin main" #2> /dev/null
-            else
-                echo "Pulling NEPI Clean"
-                git pull --recurse-submodules
-                git submodule foreach --recursive "git reset --hard HEAD && git clean -fd"
-                git submodule update --init --recursive --force
-                git submodule foreach --recursive "git checkout main && git pull origin main" 2> /dev/null
-
-            fi
-        fi
-        ubrc >/dev/null 2>&1
-      fi
-  fi
-}
-export -f pulln
-
-function pullnc {
-  if is_valid_internet ; then
     repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
     setup_folder=/home/${CONFIG_USER}/nepi_setup
 
     cd $repo_folder
+
     head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-    if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-    
-      if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
-          git pull --recurse-submodules
-          git submodule foreach --recursive "git reset --hard HEAD && git clean -fd"
-          git submodule update --init --recursive --force
-          git submodule foreach --recursive "git checkout main && git pull origin main" 2> /dev/null
-      fi
-      ubrc >/dev/null 2>&1
+    if [ "$?" -gt 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+      echo -e "${RED}Not a Git Repo $(pwd)"
+      echo -e "${WHITE}"
+      return 1
     fi
-  fi
+
+    git push --dry-run >/dev/null 2>&1
+    if [ ! $? -eq 0 ]; then
+        # git pull --recurse-submodules
+        # git submodule foreach --recursive "git checkout main && git push && git pull origin main" 2> /dev/null
+        # #git submodule foreach --recursive "git add --all && git commit -m "*$@*" &&  git push && git checkout main && git push && git pull origin main" #2> /dev/null
+        pushn
+    else
+        # echo "Pulling NEPI Clean"
+        # git pull --recurse-submodules
+        # git submodule foreach --recursive "git reset --hard HEAD && git clean -fd"
+        # git submodule update --init --recursive --force
+        # git submodule foreach --recursive "git checkout main && git pull origin main" 2> /dev/null
+        pullrc
+
+    fi
+        
+    # ubrc >/dev/null 2>&1
+
+
+}
+export -f pulln
+
+
+function pullnc {
+
+    repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
+    setup_folder=/home/${CONFIG_USER}/nepi_setup
+
+    cd $repo_folder
+
+    pullrc
+
+    # cd "${repo_folder}/nepi_setup"
+    # pushr
+    # shopt -s nullglob
+    # for dir in "$repo_folder"/src/*/ ; do
+    #     #echo "Processing Repo: $dir"
+    #     cd $dir
+    #     pushr
+    # done
+    # cd $repo_folder
+    # pushr
+
+
+      # git pull --recurse-submodules
+      # git submodule foreach --recursive "git reset --hard HEAD && git clean -fd"
+      # git submodule update --init --recursive --force
+      # git submodule foreach --recursive "git checkout main && git pull origin main" 2> /dev/null
+
+      ubrc >/dev/null 2>&1
 
 }
 export -f pullnc
