**

diff --git a/resources/bash/nepi_bash_utils b/resources/bash/nepi_bash_utils
--- a/resources/bash/nepi_bash_utils
+++ b/resources/bash/nepi_bash_utils
@@ -1826,22 +1826,22 @@ export -f nnet
 function ndhcp(){
   sudo -v
 
-    ping -c 1 -W 1 8.8.8.8 > /dev/null 2>&1
+    # ping -c 1 -W 1 8.8.8.8 > /dev/null 2>&1
 
-    # Check the exit status of the ping command
-    # 0 indicates success (internet connection)
-    # Non-zero indicates failure (no internet connection)
-    if [ $? -ne 0 ]; then
-      echo "Can't Ping Internet t 8.8.8.8"
-      return 1
-    else
+    # # Check the exit status of the ping command
+    # # 0 indicates success (internet connection)
+    # # Non-zero indicates failure (no internet connection)
+    # if [ $? -ne 0 ]; then
+    #   echo "Can't Ping Internet t 8.8.8.8"
+    #   return 1
+    # else
       echo "Resetting DHCP Clients"
       echo "Killing existing DHCP clients"
       sudo kill $(ps aux | grep 'dhclient' | awk '{print $2}') >/dev/null 2>&1
       echo "Renewing dhclient"
       sudo dhclient -nw > /dev/null 2>&1
       sudo kill $(ps aux | grep 'dhclient' | awk '{print $2}') >/dev/null 2>&1
-    fi
+    # fi
     
 }
 export -f ndhcp
