**

diff --git a/resources/bash/nepi_bash_utils b/resources/bash/nepi_bash_utils
--- a/resources/bash/nepi_bash_utils
+++ b/resources/bash/nepi_bash_utils
@@ -5260,6 +5260,14 @@ source ./deploy_nepi_complete.sh $dclean
 cd $run_folder
 }
 
+## NEPI deploy complete
+function nepidl {
+run_folder=$(pwd)
+cd $NEPI_REPO_FOLDER
+source ./deploy_nepi_live.sh
+cd $run_folder
+}
+
 # NEPI deploy repos
 alias repodpl="
 cd $NEPI_REPO_FOLDER
@@ -5345,7 +5353,6 @@ function pushn(){
     if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
         echo -e "${GREEN}Pushing to repo ${PWD##*/} Head develop"
         git push origin HEAD:develop
-
     else
         echo -e "${GREEN}Pushing to repo ${PWD##*/} Head main"
         git push origin HEAD:main
@@ -5360,7 +5367,7 @@ function pushn(){
     echo -e "${RED}Not in Git Repo"
   fi
 }
-
+export -f pushn
 
 function pulln {
   if is_valid_internet ; then
@@ -5375,63 +5382,132 @@ function pulln {
           git submodule foreach --recursive "git checkout main && git pull origin main" 2> /dev/null
       fi
     fi
-
-    # head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-    # if [ "$?" -ne 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-    #   cd $repo_folder
-    # fi
-    # head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-    # if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-    #   if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
-    #       git pull --recurse-submodules
-    #       git submodule foreach --recursive "git checkout main && git pull origin main" 2> /dev/null
-    #       #git submodule foreach --recursive "git add --all &&  git commit -m '' &&  git push >/dev/null 2>&1 && git checkout main && git pull origin main &&  git push >/dev/null 2>&1" 2> /dev/null
-    #   elif [[ "$(pwd)" == "${setup_folder}"  ]]; then
-    #     git fetch origin
-    #     git reset --hard origin/main
-    #     git push origin main --force
-    #   else
-    #     pushn
-    #   fi
-    # else
-    #   echo -e "${RED}Not in Git Repo"
-    # fi
   fi
 }
-
 export -f pulln
 
+function pullnc {
+  if is_valid_internet ; then
+    repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
+    setup_folder=/home/${CONFIG_USER}/nepi_setup
+    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+    if [ "$?" -ne 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+      cd $repo_folder
+    fi
+    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+    if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+      echo -e "${GREEN}Clearing __pycache__ folders"
+      find ./ -type d -name "__pycache__" -exec rm -rf {} +
+      git fetch --all --prune
+      git reset --hard @{upstream}
+      git submodule sync --recursive
+      git submodule update --init --force --recursive
+      git submodule foreach --recursive 'git fetch --all --prune; git reset --hard @{upstream} || git reset --hard HEAD'
+      git clean -ffdx
+      git submodule foreach --recursive 'git clean -ffdx'
+    else
+      echo -e "${RED}Not in Git Repo"
+    fi
+  fi
+}
+export -f pullnc
 
-# function pulln {
-#   if is_valid_internet ; then
-#     repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
-#     setup_folder=/home/${CONFIG_USER}/nepi_setup
-#     head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-#     if [ "$?" -ne 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-#       cd $repo_folder
-#     fi
-#     head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-#     if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-#       echo -e "${GREEN}Clearing __pycache__ folders"
-#       find ./ -type d -name "__pycache__" -exec rm -rf {} +
-#       if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
-#           git pull --recurse-submodules
-#           git submodule foreach --recursive "git checkout main && git pull origin main" 2> /dev/null
-#           #git submodule foreach --recursive "git add --all &&  git commit -m '' &&  git push >/dev/null 2>&1 && git checkout main && git pull origin main &&  git push >/dev/null 2>&1" 2> /dev/null
-#       elif [[ "$(pwd)" == "${setup_folder}"  ]]; then
-#         git fetch origin
-#         git reset --hard origin/main
-#         git push origin main --force
-#       else
-#         pushn
-#       fi
-#     else
-#       echo -e "${RED}Not in Git Repo"
-#     fi
-#   fi
-# }
+function pushr(){
+  cur_path=$(pwd)
+  cur_folder=${PWD##*/}
 
-# export -f pulln
+  git add --all
+  git commit -m "*$@*" 
+  git push >/dev/null 2>&1
+
+  par_path=$(dirname "$(pwd)")
+  par_folder=$(basename "$par_path")
+  #echo $cur_folder
+  #echo $par_folder
+  head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+  if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+    echo -e "${GREEN}Clearing __pycache__ folders"
+    find ./ -type d -name "__pycache__" -exec sudo rm -rf {} +
+    if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
+        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head develop"
+        git push origin HEAD:develop
+    else
+        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head main"
+        git push origin HEAD:main
+        #git checkout main
+    fi
+    if [ ! $? -eq 0 ]; then
+      git pull --no-edit
+      if [ $? -eq 0 ]; then
+        echo -e "${GREEN}Pushing Merged repo ${PWD##*/} Head main"
+        git push origin HEAD:main
+        if [ ! $? -eq 0 ]; then
+          echo -e "${RED}Push Failed"
+          return 1 # Failed
+        fi
+      fi
+
+    fi
+    echo -e "${GREEN}Push Successfully"
+  else
+    echo -e "${RED}Not in Git Repo"
+  fi
+}
+export -f pushr
+
+function pullr {
+  if is_valid_internet ; then
+    repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
+    setup_folder=/home/${CONFIG_USER}/nepi_setup
+    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+    if [ "$?" -ne 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+      cd $repo_folder
+    fi
+    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+    if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+      echo -e "${GREEN}Clearing __pycache__ folders"
+      find ./ -type d -name "__pycache__" -exec rm -rf {} +
+      if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
+          pulln
+      elif [[ "$(pwd)" == "${setup_folder}"  ]]; then
+        git fetch origin
+        git reset --hard origin/main
+        git push origin main --force        
+      else
+        pushr
+      fi
+    else
+      echo -e "${RED}Not in Git Repo"
+    fi
+  fi
+}
+export -f pullr
+
+function pullrc {
+  if is_valid_internet ; then
+    repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
+    setup_folder=/home/${CONFIG_USER}/nepi_setup
+    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+    if [ "$?" -ne 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+      cd $repo_folder
+    fi
+    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+    if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+      echo -e "${GREEN}Clearing __pycache__ folders"
+      find ./ -type d -name "__pycache__" -exec rm -rf {} +
+      git fetch --all --prune
+      git reset --hard @{upstream}
+      git submodule sync --recursive
+      git submodule update --init --force --recursive
+      git submodule foreach --recursive 'git fetch --all --prune; git reset --hard @{upstream} || git reset --hard HEAD'
+      git clean -ffdx
+      git submodule foreach --recursive 'git clean -ffdx'
+    else
+      echo -e "${RED}Not in Git Repo"
+    fi
+  fi
+}
+export -f pullrc
 
 ## NEPI deploy complete
 function nepisetup_remote() {
@@ -5565,9 +5641,15 @@ nepigithubdev = Check and Setup a GitHub SSH key for your GitHub account and clo
 nepiclone = Clone the latest NEPI source-code repo
 nepiclonedev = Clone the latest NEPI Development branch source-code repo
 nepidpl = Deploy nepi complete to nepi device
+nepidplc = Clear NEPi source and system config folders. Deploy nepi complete to nepi device
+nepidl = Deploy nepi python scripts to running NEPI container
 gitmain = Change to main branch in current repo or submodule folder
-pulln = Update to the latest NEPI source-code repo
-pushn = Add,commit,push repo changes with optional comment msg in current repo or submodule folder"
+pushn = Add,commit,push repo changes with optional comment msg in current repo or submodule folder
+pulln = Push repo changes, then pull and merge any update to the latest NEPI source-code repo
+pullnc = Discard any source changes and revert repo and submodules to latest remote commit.
+pushr = Add,commit,push repo changes with optional comment msg in current repo or submodule folder
+pullr = Push repo changes, then pull and merge any update to the latest repo
+pullrc = Discard any source changes and revert repo and submodules to latest remote commit."
 
 
 
