**

diff --git a/resources/bash/nepi_bash_utils b/resources/bash/nepi_bash_utils
--- a/resources/bash/nepi_bash_utils
+++ b/resources/bash/nepi_bash_utils
@@ -1242,37 +1242,37 @@ export -f nnet
 # }
 # export -f nnet_release
 
-# function ndhcp(){
-#   sudo -v
-#   if nnet; then
-#     # This file sets up nepi bash aliases and util functions
-#     # Check for internet connection by pinging a reliable public DNS server (e.g., Google's 8.8.8.8)
-#     # -c 1: Send only one ping packet
-#     # -W 1: Wait for 1 second for a response
-#     ping -c 1 -W 1 8.8.8.8 > /dev/null 2>&1
+function ndhcp(){
+  sudo -v
+  if nnet; then
+    # This file sets up nepi bash aliases and util functions
+    # Check for internet connection by pinging a reliable public DNS server (e.g., Google's 8.8.8.8)
+    # -c 1: Send only one ping packet
+    # -W 1: Wait for 1 second for a response
+    ping -c 1 -W 1 8.8.8.8 > /dev/null 2>&1
 
-#     # Check the exit status of the ping command
-#     # 0 indicates success (internet connection)
-#     # Non-zero indicates failure (no internet connection)
-#     if [ $? -ne 0 ]; then
-#       echo "No internet connection detected. Will try and connect"
+    # Check the exit status of the ping command
+    # 0 indicates success (internet connection)
+    # Non-zero indicates failure (no internet connection)
+    if [ $? -ne 0 ]; then
+      echo "No internet connection detected. Will try and connect"
 
-#       echo "Enabling DHCP internet connection"
-#       echo "Killing existing DHCP clients"
-#       sudo kill $(ps aux | grep 'dhclient' | awk '{print $2}') >/dev/null 2>&1
-#       echo "Renewing dhclient"
-#       sudo dhclient -nw
-#       sleep 2
-#       nnet # Restart network
-#       wait
-#       if ! pingi; then
-#         return 1
-#       fi
-#     fi
-#     sudo kill $(ps aux | grep 'dhclient' | awk '{print $2}') >/dev/null 2>&1
-#   fi
-# }
-# export -f ndhcp
+      echo "Enabling DHCP internet connection"
+      echo "Killing existing DHCP clients"
+      sudo kill $(ps aux | grep 'dhclient' | awk '{print $2}') >/dev/null 2>&1
+      echo "Renewing dhclient"
+      sudo dhclient -nw
+      sleep 2
+      nnet # Restart network
+      wait
+      if ! pingi; then
+        return 1
+      fi
+    fi
+    sudo kill $(ps aux | grep 'dhclient' | awk '{print $2}') >/dev/null 2>&1
+  fi
+}
+export -f ndhcp
 
 
 function nclock(){
@@ -1337,7 +1337,7 @@ function ninet(){
       fi
       
   fi
-  #ndhcp # Enable DHCP internet connection if needed
+  ndhcp # Enable DHCP internet connection if needed
   wait
   sleep 1
   if ! nclock; then # Connect to NTP server
@@ -2285,9 +2285,9 @@ export -f get_hailo_hw_version
 
 function get_hailo_sw_version(){
         hailo_version=0
-        if is_valid_hailo  >/dev/null 2>&1; then
-          hailo_info=$(hailortcli fw-control identify  2> /dev/null | tr -d '\0' 2>/dev/null)
-          hailo_sw=$(echo $hailo_info | grep -oP 'Firmware Version: \K[0-9]+\.[0-9]+\.[0-9]+')
+        hailo_info=$(hailortcli -version) >/dev/null 2>&1
+        if [[ -n $hailo_info ]] ; then
+          hailo_sw="${hailo_info##* }"
           if [[ -n hailo_sw ]]; then
             hailo_version=$hailo_sw
           fi
@@ -2297,26 +2297,49 @@ function get_hailo_sw_version(){
 }
 export -f get_hailo_sw_version
 
-function get_hailo_installed_version(){
+function get_hailo_fw_version(){
         hailo_version=0
-        hailo_folder="/lib/firmware/hailo"
-        if [[ -d $hailo_folder ]]; then
-          if [[ -L "${hailo_folder}/hailo8_fw.bin" ]]; then
-            hailo_path=$(readlink "${hailo_folder}/hailo8_fw.bin")
-          elif [[ -L "${hailo_folder}/hailo10_fw.bin" ]]; then
-            hailo_path=$(readlink "${hailo_folder}/hailo10_fw.bin")
-          fi
-          if [[ -n $hailo_path ]]; then
-            hailo_file="${hailo_path#*fw.}"
-            version="${hailo_file%.bin*}"
-            if [[ -n $version ]]; then
-              hailo_version=$version
+        if is_valid_hailo_hw  >/dev/null 2>&1; then
+          hailo_info=$(hailortcli fw-control identify  2> /dev/null | tr -d '\0' 2>/dev/null)
+          hailo_sw=$(echo $hailo_info | grep -oP 'Firmware Version: \K[0-9]+\.[0-9]+\.[0-9]+')
+          hailo_sw=${hailo_sw// /}
+          if [[ -n $hailo_sw ]]; then
+            hailo_version=$hailo_sw
+          else
+            hailo_info=$(hailortcli fw-control identify 2>&1 >/dev/null | head -n 1)
+            tmp="${hailo_info#*\(}"
+            hailo_sw="${tmp%%\)*}"
+            if [[ -n 4hailo_sw ]]; then
+              hailo_version=$hailo_sw
             fi
           fi
+
         fi
+      
         echo $hailo_version
 }
-export -f get_hailo_installed_version
+export -f get_hailo_fw_version
+
+# function get_hailo_installed_version(){
+#         hailo_version=0
+#         hailo_folder="/lib/firmware/hailo"
+#         if [[ -d $hailo_folder ]]; then
+#           if [[ -L "${hailo_folder}/hailo8_fw.bin" ]]; then
+#             hailo_path=$(readlink "${hailo_folder}/hailo8_fw.bin")
+#           elif [[ -L "${hailo_folder}/hailo10_fw.bin" ]]; then
+#             hailo_path=$(readlink "${hailo_folder}/hailo10_fw.bin")
+#           fi
+#           if [[ -n $hailo_path ]]; then
+#             hailo_file="${hailo_path#*fw.}"
+#             version="${hailo_file%.bin*}"
+#             if [[ -n $version ]]; then
+#               hailo_version=$version
+#             fi
+#           fi
+#         fi
+#         echo $hailo_version
+# }
+# export -f get_hailo_installed_version
 
 
 function get_openvpn_version(){
