**

diff --git a/resources/bash/nepi_bash_utils b/resources/bash/nepi_bash_utils
--- a/resources/bash/nepi_bash_utils
+++ b/resources/bash/nepi_bash_utils
@@ -1676,6 +1676,253 @@ dps = sudo docker ps -a"
 
 fi
 
+###################################
+# NEPI Dev Functions
+###################################
+export SOURCE_FOLDER=/home/${CONFIG_USER}/nepi_engine_ws
+GREEN='\033[0;32m'
+RED='\033[0;31m'
+
+
+function nepigithub {
+    if is_valid_internet >/dev/null 2>&1; then
+
+        echo " "
+        echo "################################# "
+        echo "Checking Github SSH Key"
+        echo ""
+
+
+        install_key='yes'
+
+        while [[ "$install_key" == 'yes' ]]; do
+
+
+            if ! is_valid_internet >/dev/null 2>&1; then
+                echo "NO INTERNET CONNECTION DETECTED.  "
+                echo ""
+                install_key=$(ask_yes_no "Do you want to connect to internet and try again?")
+            else
+                ssh -T git@github.com >/dev/null 2>&1
+                if [[ "$?" -lt 2 ]]; then
+                    key_file=$(ssh -G git@github.com 2>/dev/null | grep -im1 '^IdentityFile' | cut -d' ' -f2) >/dev/null
+                    key_name=$(basename "${key_file}")
+                    install_key='no'
+                else
+                    key_file=''
+                    echo "NO VALID GITHUB SSH KEY FOUND"
+                    echo ""
+                    install_key=$(ask_yes_no "Do you want to create a new GitHub SSH Key?")
+
+                    if [ "$install_key" == "yes" ]; then
+
+                        key_name=id_ed25519_nepi
+                        key_file=/home/${CONFIG_USER}/.ssh/${key_name}
+                        if [[ ! -f $key_file ]]; then
+                            echo "Creating NEPI GitHub ssh_key ${key_name}"
+                            echo ""
+                            while [[ -z "$ghub_email" ]]; do
+                                read -p "Enter your GitHub email address: " USER_INPUT
+                                if is_valid_email "$USER_INPUT"; then
+                                    echo "Using email ${USER_INPUT}"
+                                    ghub_email=$USER_INPUT
+                                else
+                                    echo "Not A Valid Email"
+                                fi  
+                            done   
+                            ssh-keygen -t ed25519 -f ${key_file} -q -N "" -C "${ghub_email}"
+
+                        fi
+                        config_file=/home/${CONFIG_USER}/.ssh/config
+                        touch ${config_file}
+                        if grep -qnw $config_file -e ${key_name}; then
+                            : #echo "Already Done"
+                        else
+                            echo 'Host github.com' | sudo tee -a $config_file
+                            echo '   AddKeysToAgent yes' | sudo tee -a $config_file
+                            echo '   IdentityFile '${key_file} | sudo tee -a $config_file
+                        fi
+                        
+                        eval "$(ssh-agent -s)"
+                        ssh-add ${key_file}
+                    else
+                        echo "You can rerun this script if you want to setup at a later time"
+                        echo ""
+                    fi
+                fi
+
+            fi
+        done
+
+        if [[ -n $key_file ]]; then
+            check_key='yes'
+            while [[ "$check_key" == 'yes' ]]; do
+
+
+                ssh -T git@github.com >/dev/null 2>&1
+                if [[ "$?" -gt 1 ]]; then
+
+                    echo "*** ADD YOUR NEW NEPI GITHUB SSH KEY TO YOUR GITHUB ACCOUNT BEFORE PROCEEDING ***"
+                    echo ""
+                    echo "1) Log Into Your GitHub Account at www.github.com"
+                    echo "2) Click on your User Icon, and select 'Settings"
+                    echo "3) Select 'SSH and GPG keys' from the left sidebar menu"
+                    echo "4) Click the 'New SSH key' button in the top right"
+                    echo "5) Enter the following information in the boxes provided,"
+                    echo "   Then click the 'Add SSH key' button"
+                    echo ""
+                    echo "<< TITLE >>"
+                    echo ${key_name}
+                    echo ""
+                    echo "<< KEY_TYPE >>"
+                    echo "Authentication Key"
+                    echo ""
+                    echo "<< KEY >>"
+                    echo $(cat ${key_file}.pub)
+                    echo ""
+                    echo "6) Rerun this script to test that your GitHub SSH Key Authenticates"
+
+                    echo ""
+                    check_key=$(ask_yes_no "Do you want to setup your key in your GitHub account and test it again?")
+                else
+                    check_key='no'
+                fi
+            done
+        fi
+
+        ssh -T git@github.com >/dev/null 2>&1
+        if [[ "$?" -lt 2 ]]; then
+            echo ''
+            echo '#######################'
+            echo "GitHub SSH key authenticated with key file ${key_file}"
+            echo '#######################'
+            echo ''
+        else
+            echo "GitHub SSH key not authenticated"
+        fi
+
+
+        echo " "
+        echo "################################# "
+        echo "NEPI DEV GITHUB SETUP COMPLETE"
+        echo "################################# "
+        echo " "
+    fi
+
+}
+
+export -f nepigithub
+
+
+function nepiclone {
+  if is_valid_internet ; then
+    cd ~/
+    git clone git@github.com:nepi-engine/nepi_engine_ws.git 
+    cd nepi_engine_ws
+    git checkout main
+    git submodule update --init --recursive
+  fi
+}
+
+export -f nepiclone
+
+function nepiclonedev {
+  if is_valid_internet ; then
+    cd ~/
+    git clone git@github.com:nepi-engine/nepi_engine_ws.git 
+    cd nepi_engine_ws
+    git checkout develop
+    git submodule update --init --recursive
+  fi
+}
+
+export -f nepiclonedev
+
+
+function nepipull {
+  if is_valid_internet ; then
+    cd ~/nepi_engine_ws
+    git pull --recurse-submodules
+  fi
+}
+
+export -f nepipull
+
+function nepimain {
+    cd ~/nepi_engine_ws
+    git checkout main
+}
+export -f nepimain
+
+function nepidev {
+    cd ~/nepi_engine_ws
+    git checkout develop
+}
+export -f nepidev
+
+
+
+## NEPI deploy complete
+alias nepisetup="
+source ${SOURCE_FOLDER}/nepi_setup/scripts/dev_pc_setup.sh"
+
+## NEPI deploy complete
+alias nepidpl="
+cd $SOURCE_FOLDER
+source ./deploy_nepi_complete.sh"
+
+# NEPI deploy repos
+alias repodpl="
+cd $SOURCE_FOLDER
+source ./deploy_nepi_repos.sh"
+
+
+function pushn(){
+  git add --all
+  git commit -m "*$@*" 
+  git push >/dev/null 2>&1
+  cur_folder=${PWD##*/}
+  par_path=$(dirname "$(pwd)")
+  par_folder=$(basename "$par_path")
+  #echo $cur_folder
+  #echo $par_folder
+  head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+  if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+    if [[ "$cur_folder" == 'nepi_engine_ws' || "$(pwd)" == "/home/${CONFIG_USER}/nepi_engine_ws/src" ]]; then
+        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head develop"
+        git push origin HEAD:develop
+
+    else
+        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head main"
+        git push origin HEAD:main
+        #git checkout main
+    fi
+    if [ ! $? -eq 0 ]; then
+      echo -e "${RED}Push Failed"
+      return 1 # Failed
+    fi
+    echo -e "${GREEN}Push Successfully"
+  else
+    echo -e "${RED}Not in Git Repo"
+  fi
+}
+
+
+
+utilsn="${utilsn}
+################################
+### NEPI Dev FUNCTIONS
+################################
+nepigithub = Check and Setup a GitHub SSH key for your GitHub account
+nepiclone = Clone the latest NEPI source-code repo
+nepiclonedev = Clone the latest NEPI Development branch source-code repo
+nepipull = Update to the latest NEPI source-code repo
+nepimain = Switch to the NEPI Engine repo's main branch
+nepidev = Switch to the NEPI Engine repo's main branch
+nepidpl = Deploy nepi complete to nepi device
+pushn = Add,commit,push repo changes with optional comment msg"
+
+
 
 
 
