**

diff --git a/resources/bash/nepi_bash_utils b/resources/bash/nepi_bash_utils
--- a/resources/bash/nepi_bash_utils
+++ b/resources/bash/nepi_bash_utils
@@ -5400,27 +5400,23 @@ function pushr(){
   cur_path=$(pwd)
   cur_folder=${PWD##*/}
 
-  git add --all
-  git commit -m "*$@*" 
-  git push >/dev/null 2>&1
-
-  par_path=$(dirname "$(pwd)")
-  par_folder=$(basename "$par_path")
-  #echo $cur_folder
-  #echo $par_folder
   head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
   if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-    echo -e "${GREEN}Clearing __pycache__ folders"
+    #echo -e "${GREEN}Clearing __pycache__ folders"
+    echo -e "${WHITE}#######################"
+    git add --all
+    git commit -m "*$@*" 
     find ./ -type d -name "__pycache__" -exec sudo rm -rf {} +
     if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
-        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head develop"
+        echo -e "${WHITE}Pushing to repo ${PWD##*/}"
         git push origin HEAD:develop
     else
-        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head main"
+        echo -e "${WHITE}Pushing to repo ${PWD##*/}"
         git push origin HEAD:main
         #git checkout main
     fi
     if [ ! $? -eq 0 ]; then
+      echo ""
       git pull --no-edit
       if [ $? -eq 0 ]; then
         echo -e "${GREEN}Pushing Merged repo ${PWD##*/} Head main"
@@ -5441,25 +5437,9 @@ export -f pushr
 
 function pullr {
   if is_valid_internet ; then
-    repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
-    setup_folder=/home/${CONFIG_USER}/nepi_setup
-    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-    if [ "$?" -ne 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-      cd $repo_folder
-    fi
     head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
     if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-      echo -e "${GREEN}Clearing __pycache__ folders"
-      find ./ -type d -name "__pycache__" -exec rm -rf {} +
-      if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
-          pulln
-      elif [[ "$(pwd)" == "${setup_folder}"  ]]; then
-        git fetch origin
-        git reset --hard origin/main
-        git push origin main --force        
-      else
-        pushr
-      fi
+      git pull
     else
       echo -e "${RED}Not in Git Repo"
     fi
@@ -5469,12 +5449,6 @@ export -f pullr
 
 function pullrc {
   if is_valid_internet ; then
-    repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
-    setup_folder=/home/${CONFIG_USER}/nepi_setup
-    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-    if [ "$?" -ne 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-      cd $repo_folder
-    fi
     head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
     if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
       echo -e "${GREEN}Clearing __pycache__ folders"
@@ -5493,68 +5467,103 @@ function pullrc {
 }
 export -f pullrc
 
-function pushn(){
-  cur_path=$(pwd)
-  cur_folder=${PWD##*/}
+# function pushn(){
+#   cur_path=$(pwd)
+#   cur_folder=${PWD##*/}
 
-  git add --all
-  git commit -m "*$@*" 
-  git push >/dev/null 2>&1
+#   git add --all
+#   git commit -m "*$@*" 
+#   git push >/dev/null 2>&1
 
-  par_path=$(dirname "$(pwd)")
-  par_folder=$(basename "$par_path")
-  #echo $cur_folder
-  #echo $par_folder
-  head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-  if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-    echo -e "${GREEN}Clearing __pycache__ folders"
-    find ./ -type d -name "__pycache__" -exec sudo rm -rf {} +
-    if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
-        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head develop"
-        git push origin HEAD:develop
-    else
-        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head main"
-        git push origin HEAD:main
-        #git checkout main
-    fi
-    if [ ! $? -eq 0 ]; then
-      echo -e "${RED}Push Failed"
-      return 1 # Failed
-    fi
-    echo -e "${GREEN}Push Successfully"
-  else
-    echo -e "${RED}Not in Git Repo"
-  fi
-}
-export -f pushn
+#   par_path=$(dirname "$(pwd)")
+#   par_folder=$(basename "$par_path")
+#   #echo $cur_folder
+#   #echo $par_folder
+#   head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+#   if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+#     echo -e "${GREEN}Clearing __pycache__ folders"
+#     find ./ -type d -name "__pycache__" -exec sudo rm -rf {} +
+#     if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
+#         echo -e "${GREEN}Pushing to repo ${PWD##*/} Head develop"
+#         git push origin HEAD:develop
+#     else
+#         echo -e "${GREEN}Pushing to repo ${PWD##*/} Head main"
+#         git push origin HEAD:main
+#         #git checkout main
+#     fi
+#     if [ ! $? -eq 0 ]; then
+#       echo -e "${RED}Push Failed"
+#       return 1 # Failed
+#     fi
+#     echo -e "${GREEN}Push Successfully"
+#   else
+#     echo -e "${RED}Not in Git Repo"
+#   fi
+# }
+# export -f pushn
 
-function pulln {
+
+function pushn {
   if is_valid_internet ; then
 
-        repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
-        setup_folder=/home/${CONFIG_USER}/nepi_setup
-
+      repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
+      setup_folder=/home/${CONFIG_USER}/nepi_setup
+      ssh -T git@github.com >/dev/null 2>&1
+      if [[ "$?" -lt 2 ]]; then
         cd $repo_folder
         head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
         if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
           if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
-              ssh -T git@github.com >/dev/null 2>&1
-              if [[ "$?" -lt 2 ]]; then
-                  git pull --recurse-submodules
-                  git submodule foreach --recursive "git checkout main && git push && git pull origin main" 2> /dev/null
-                  #git submodule foreach --recursive "git add --all && git commit -m "*$@*" &&  git push && git checkout main && git push && git pull origin main" #2> /dev/null
-              else
-                  echo "Pulling NEPI Clean"
-                  git pull --recurse-submodules
-                  git submodule foreach --recursive "git reset --hard HEAD && git clean -fd"
-                  git submodule update --init --recursive --force
-                  git submodule foreach --recursive "git checkout main && git pull origin main" 2> /dev/null
 
-              fi
+              cd "${repo_folder}/nepi_setup"
+              pushr
+              shopt -s nullglob
+              for dir in "$repo_folder"/src/*/ ; do
+                  #echo "Processing Repo: $dir"
+                  cd $dir
+                  pushr
+              done
+              cd $repo_folder
+              pushr
+                
           fi
           ubrc >/dev/null 2>&1
         fi
+        echo "Git SSH Credentials Failed"
       fi
+  fi
+}
+export -f pushn
+
+
+
+function pulln {
+  if is_valid_internet ; then
+
+      repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
+      setup_folder=/home/${CONFIG_USER}/nepi_setup
+
+      cd $repo_folder
+      head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
+      if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+        if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
+            ssh -T git@github.com >/dev/null 2>&1
+            if [[ "$?" -lt 2 ]]; then
+                git pull --recurse-submodules
+                git submodule foreach --recursive "git checkout main && git push && git pull origin main" 2> /dev/null
+                #git submodule foreach --recursive "git add --all && git commit -m "*$@*" &&  git push && git checkout main && git push && git pull origin main" #2> /dev/null
+            else
+                echo "Pulling NEPI Clean"
+                git pull --recurse-submodules
+                git submodule foreach --recursive "git reset --hard HEAD && git clean -fd"
+                git submodule update --init --recursive --force
+                git submodule foreach --recursive "git checkout main && git pull origin main" 2> /dev/null
+
+            fi
+        fi
+        ubrc >/dev/null 2>&1
+      fi
+  fi
 }
 export -f pulln
 
