**

diff --git a/resources/bash/nepi_bash_utils b/resources/bash/nepi_bash_utils
--- a/resources/bash/nepi_bash_utils
+++ b/resources/bash/nepi_bash_utils
@@ -439,18 +439,43 @@ function is_valid_cuda(){
 }
 export -f is_valid_cuda
 
-function is_valid_hailo(){
-    is_valid=1
-    if lspci -k 2>/dev/null | grep -iq "hailo"; then
-      is_valid=0
-    elif [[ -d "/lib/firmware/hailo" ]]; then
-      is_valid=0
+function is_valid_hailo_hw(){
+    if ! lspci -k 2>/dev/null | grep -iq "hailo"; then
+      echo "Hailo Device Not Found"
+      return 1
     fi
-    return $is_valid
+    echo "Hailo Device Found"
+}
+export -f is_valid_hailo_hw
+
+function is_valid_hailo_sw(){
+    if hailortcli fw-control identify >/dev/null 2>&1; then
+      echo "Hailo Software Found"
+      return 0
+    else
+      echo "Hailo Software Not Found"
+      return 1
+    fi
+}
+export -f is_valid_hailo_sw
+
+function is_valid_hailo(){
+    if ! is_valid_hailo_hw; then
+      return 1
+    fi
+    if ! is_valid_hailo_sw; then
+      retun 1
+    fi
+    hailo_info=$(hailortcli fw-control identify | tr -d '\0' 2>/dev/null)
+    if [[ $? -eq 0 && -n $hailo_info ]]; then
+      echo "Hailo Softwar Found Hailo Device"
+      return 0
+    else
+      echo "Hailo Software Failed to Find Hailo Device"
+      return 1
+    fi
 }
 export -f is_valid_hailo
-
-
 
 function is_space_avail_mb(){
     local check_path=$1
@@ -561,7 +586,9 @@ is_valid_rpi = Check if system is on a Raspberry Pi
 is_valid_arm64 = Check if device is arm64 arch
 is_valid_amd64 = Check if device is amd64 arch
 is_valid_cuda = Check if system has CUDA
-is_valid_hailo = Check if system has Halio Module
+is_valid_hailo_hw = Check if system has Halio Module
+is_valid_hailo_sw = Check if system has Halio Software
+is_valid_hailo = Check if Hailo software found Hailo module
 is_space_avail_mb = Check folder for REQ_SPACE in MB
 is_space_avail_gb = Check folder for REQ_SPACE in GB
 is_nepi_path = Check if path in either a nepi managed folder
@@ -1984,13 +2011,32 @@ function get_cuda_version(){
           declare -a files
           for file in "$cuda_path"/*; do
               if [[ -d "$file" && "$file" == *cuda-* ]]; then # Check if the item is a regular file
-                  cuda_version=${file##*-}
+                  cuda_version="CUDA"${file##*-}
               fi
           done
           echo $cuda_version
         fi
 }
 export -f get_cuda_version
+
+
+function get_hailo_version(){
+        hailo_version=0
+        if [[ "$NEPI_MODE" == 'SYSTEM' ]]; then
+          hailo_version=$NEPI_HAILO_VERSION
+        else
+          if is_valid_hailo  >/dev/null 2>&1; then
+            hailo_info=$(hailortcli fw-control identify | tr -d '\0' 2>/dev/null)
+            hailo_arch=$(grep -m 1 -o '.*HAILO.*' <<< "$hailo_info")
+            hailo_name="${hailo_arch#*: }"
+            if [[ -n hailo_name ]]; then
+              hailo_version=$hailo_name
+            fi
+          fi
+        fi
+        echo $hailo_version
+}
+export -f get_hailo_version
 
 
 function get_openvpn_version(){
@@ -2008,11 +2054,12 @@ function get_sw_desc() {
   os_desc=$(get_os_info)
   sw_desc=${os_desc}
   cuda_ver=$(get_cuda_version)
-  if [[ "$cuda_ver" != '0' ]]; then
-    sw_desc="${sw_desc}_CUDA${cuda_ver}"
+  if [[ -n $cuda_ver && "$cuda_ver" != '0' ]]; then
+    sw_desc="${sw_desc}_${cuda_ver}"
   fi
-  if is_valid_hailo; then
-    sw_desc="${sw_desc}_Hailo"
+  hailo_ver=$(get_hailo_version)
+  if [[ -n $hailo_ver && "$hailo_ver" != '0' ]]; then
+    sw_desc="${sw_desc}_${hailo_ver}"
   fi
   sw_desc=$(clean_tag_string "$sw_desc")
   echo "${sw_desc}"
@@ -2315,6 +2362,7 @@ get_hw_arch = Echos the current hardware arch string (ie. arm64, amd64, or uname
 get_os_info = Echos the current OS NameVersion
 get_cuda_version = Echos CUDA version number if nvcc --version availble or 0
 get_openvpn_version = Echos OpenVPN version number if openvpn installed or 0
+get_hailo_version = Echos Hailo software version if software finds Hailo Device or 0
 get_sw_desc = Echos NEPI formated software vesion tag
 add_ssh_key = Add the ssh key in the provided full path ssh_key file
 create_ssh_key = Create a new SSH key key pair in provided key_folder
