**

diff --git a/resources/bash/nepi_bash_utils b/resources/bash/nepi_bash_utils
--- a/resources/bash/nepi_bash_utils
+++ b/resources/bash/nepi_bash_utils
@@ -5342,60 +5342,6 @@ function gitmain {
 }
 
 
-
-# function pushn(){
-#   cur_path=$(pwd)
-#   cur_folder=${PWD##*/}
-#   # IFS='/' read -r -a path_parts <<< "$cur_path"
-#   # if [[ ${#path_parts[@]} -lt 4 ]]; then
-#   #     echo "Current folder is not in the NEPI Repo folder: ${cur_path}"
-#   #     return 1
-#   # fi
-#   # third_folder="${path_parts[3]}"
-#   # if [[ ${third_folder} != ${NEPI_REPO_NAME} ]]; then
-#   #     echo "Current folder is not in the NEPI Repo folder: ${cur_path}"
-#   #     return 1
-#   # fi
-#   git add --all
-#   git commit -m "*$@*" 
-#   git push >/dev/null 2>&1
-
-#   par_path=$(dirname "$(pwd)")
-#   par_folder=$(basename "$par_path")
-#   #echo $cur_folder
-#   #echo $par_folder
-#   head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-#   if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-#     echo -e "${GREEN}Clearing __pycache__ folders"
-#     find ./ -type d -name "__pycache__" -exec rm -rf {} +
-#     if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
-#         echo -e "${GREEN}Pushing to repo ${PWD##*/} Head develop"
-#         git push origin HEAD:develop
-
-#     else
-#         echo -e "${GREEN}Pushing to repo ${PWD##*/} Head main"
-#         git push origin HEAD:main
-#         #git checkout main
-#     fi
-#     if [ ! $? -eq 0 ]; then
-#       git pull --no-edit
-#       if [ $? -eq 0 ]; then
-#         echo -e "${GREEN}Pushing Merged repo ${PWD##*/} Head main"
-#         git push origin HEAD:main
-#         if [ ! $? -eq 0 ]; then
-#           echo -e "${RED}Push Failed"
-#           return 1 # Failed
-#         fi
-#       fi
-
-#     fi
-#     echo -e "${GREEN}Push Successfully"
-#   else
-#     echo -e "${RED}Not in Git Repo"
-#   fi
-# }
-# export -f pushn
-
 function pushr(){
   cur_path=$(pwd)
   cur_folder=${PWD##*/}
@@ -5536,6 +5482,15 @@ function pullrc {
     git submodule foreach --recursive 'git fetch --all --prune; git reset --hard @{upstream} || git reset --hard HEAD'
     git clean -ffdx
     git submodule foreach --recursive 'git clean -ffdx'
+
+    if [[ $? -eq 0 ]]; then
+      echo -e "${GREEN}Pull Successfull"
+      echo -e "${WHITE}"
+    else
+      echo -e "${RED}Pull Failed"
+      echo -e "${WHITE}"
+    fi
+
 }
 export -f pullrc
 
@@ -5554,49 +5509,45 @@ function pushn {
       return 1
     fi
 
-
-
-
-    git push --dry-run >/dev/null 2>&1
-    if [ ! $? -eq 0 ]; then
-      echo -e "${RED}Push Failed: You Don't have Push Credentials $(pwd)"
-      echo -e "${WHITE}"
-      return 1
-    fi
-
     repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
     setup_folder=/home/${CONFIG_USER}/nepi_setup
-
-    cd $repo_folder
-
-    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-    if [ "$?" -gt 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-      echo -e "${RED}Not a Git Repo $(pwd)"
+    
+    success=0
+    cd $repo_folder      
+    if [[ $? -gt 0 ]]; then
+      echo -e "${RED}NEPI Repo Folder not found at: ${repo_folder}"
       echo -e "${WHITE}"
       return 1
-    fi
+    else
 
-    cd "${repo_folder}/nepi_setup"
-    pushr
-    if [[ $? -eq 0 ]]; then
-      shopt -s nullglob
-      for dir in "$repo_folder"/src/*/ ; do
-          #echo "Processing Repo: $dir"
-          cd $dir
-          pushr
-      done
-      cd $repo_folder
+      cd "${repo_folder}/nepi_setup"
       pushr
-          
-      ubrc >/dev/null 2>&1
-
+      if [[ $? -eq 0 ]]; then
+        shopt -s nullglob
+        for dir in "$repo_folder"/src/*/ ; do
+            #echo "Processing Repo: $dir"
+            cd $dir
+            pushr
+        done
+        cd $repo_folder
+        pushr
+        if [[ $? -eq 0 ]]; then
+          success=1
+          ubrc >/dev/null 2>&1
+        fi
+      fi
     fi
 
+    if [[ $success -eq 1 ]]; then
+      echo -e "${GREEN}NEPI Pull Successfull"
+      echo -e "${WHITE}"
+    else
+      echo -e "${RED}NEPI Pull Failed"
+      echo -e "${WHITE}"
+    fi
 
 }
 export -f pushn
-
-
 
 
 function pulln {
@@ -5616,65 +5567,73 @@ function pulln {
     repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
     setup_folder=/home/${CONFIG_USER}/nepi_setup
 
-    cd $repo_folder
-
-    head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-    if [ "$?" -gt 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
-      echo -e "${RED}Not a Git Repo $(pwd)"
+    cd $repo_folder      
+    if [[ $? -gt 0 ]]; then
+      echo -e "${RED}NEPI Repo Folder not found at: ${repo_folder}"
       echo -e "${WHITE}"
       return 1
-    fi
-
-    git push --dry-run >/dev/null 2>&1
-    if [ ! $? -eq 0 ]; then
-        # git pull --recurse-submodules
-        # git submodule foreach --recursive "git checkout main && git push && git pull origin main" 2> /dev/null
-        # #git submodule foreach --recursive "git add --all && git commit -m "*$@*" &&  git push && git checkout main && git push && git pull origin main" #2> /dev/null
-        pushn
     else
-        # echo "Pulling NEPI Clean"
-        # git pull --recurse-submodules
-        # git submodule foreach --recursive "git reset --hard HEAD && git clean -fd"
-        # git submodule update --init --recursive --force
-        # git submodule foreach --recursive "git checkout main && git pull origin main" 2> /dev/null
-        pullrc
 
+      git push --dry-run >/dev/null 2>&1
+      if [ ! $? -eq 0 ]; then
+          # git pull --recurse-submodules
+          # git submodule foreach --recursive "git checkout main && git push && git pull origin main" 2> /dev/null
+          # #git submodule foreach --recursive "git add --all && git commit -m "*$@*" &&  git push && git checkout main && git push && git pull origin main" #2> /dev/null
+          pushn
+      else
+          pullrc
+      fi
+          
+      if [[ $? -eq 0 ]]; then
+        ubrc >/dev/null 2>&1
+        echo -e "${GREEN}NEPI Pull Successfull"
+        echo -e "${WHITE}"
+      else
+        echo -e "${RED}NEPI Pull Failed"
+        echo -e "${WHITE}"
+      fi
     fi
-        
-    # ubrc >/dev/null 2>&1
-
-
 }
 export -f pulln
 
 
 function pullnc {
+    if ! is_valid_internet >/dev/null 2>&1; then
+      echo -e "${RED}Internet Not Connected"
+      echo -e "${WHITE}"
+      return 1
+    fi
+
+    ssh -T git@github.com >/dev/null 2>&1
+    if [[ "$?" -gt 1 ]]; then
+      echo -e "${RED}Git SSH Credentials Failed"
+      echo -e "${WHITE}"
+      return 1
+    fi
 
     repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
     setup_folder=/home/${CONFIG_USER}/nepi_setup
 
-    cd $repo_folder
-
-    pullrc
-
-    # cd "${repo_folder}/nepi_setup"
-    # pushr
-    # shopt -s nullglob
-    # for dir in "$repo_folder"/src/*/ ; do
-    #     #echo "Processing Repo: $dir"
-    #     cd $dir
-    #     pushr
-    # done
-    # cd $repo_folder
-    # pushr
+    cd $repo_folder      
+    if [[ $? -gt 0 ]]; then
+      echo -e "${RED}NEPI Repo Folder not found at: ${repo_folder}"
+      echo -e "${WHITE}"
+      return 1
+    else
 
 
-      # git pull --recurse-submodules
-      # git submodule foreach --recursive "git reset --hard HEAD && git clean -fd"
-      # git submodule update --init --recursive --force
-      # git submodule foreach --recursive "git checkout main && git pull origin main" 2> /dev/null
+      pullrc
 
-      ubrc >/dev/null 2>&1
+          
+      if [[ $? -eq 0 ]]; then
+        ubrc >/dev/null 2>&1
+        echo -e "${GREEN}NEPI Pull Successfull"
+        echo -e "${WHITE}"
+      else
+        echo -e "${RED}NEPI Pull Failed"
+        echo -e "${WHITE}"
+      fi
+    fi
 
 }
 export -f pullnc
