**

diff --git a/resources/bash/nepi_bash_utils b/resources/bash/nepi_bash_utils
--- a/resources/bash/nepi_bash_utils
+++ b/resources/bash/nepi_bash_utils
@@ -5366,41 +5366,44 @@ function pushr(){
     return 1
   fi
 
-  git push --dry-run >/dev/null 2>&1
-  if [ ! $? -eq 0 ]; then
-    echo -e "${RED}Push Failed: You Don't have Push Credentials $(pwd)"
-    echo -e "${WHITE}"
-    return 1
-  fi
+
 
   #echo -e "${GREEN}Clearing __pycache__ folders"
   echo -e "${WHITE}Pushing to repo ${PWD##*/}"
   echo -e "${WHITE}#######################"
-  
-  git add --all >/dev/null 2>&1
-  git commit -m "*$@*"  >/dev/null 2>&1
-  find ./ -type d -name "__pycache__" -exec sudo rm -rf {} +
+
   if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then   
       git push origin HEAD:develop
   else
       git push origin HEAD:main
       #git checkout main
   fi
-  if [ ! $? -eq 0 ]; then
-    echo ""
-    git pull --no-edit
-    if [ $? -eq 0 ]; then
-      echo -e "${WHITE}Pushing Merged repo ${PWD##*/}"
-      git push origin HEAD:main
-      if [ ! $? -eq 0 ]; then
-        echo -e "${WHITE}#######################"
-        echo -e "${RED}Push Failed"
-        echo -e "${WHITE}"
-        return 1 # Failed
-      fi
-    fi
 
+  git add --all >/dev/null 2>&1
+  git commit -m "*$@*" >/dev/null 2>&1
+
+  git push --dry-run >/dev/null 2>&1
+  if [[ ! $? -eq 0 ]]; then
+    echo -e "${RED}Push Failed: You Don't have Push Credentials $(pwd)"
+    echo -e "${WHITE}"
+    return 1
   fi
+
+  find ./ -type d -name "__pycache__" -exec sudo rm -rf {} +
+
+  git pull --no-edit
+  if [ $? -eq 0 ]; then
+    echo -e "${WHITE}Pushing Merged repo ${PWD##*/}"
+    git push origin HEAD:main
+    if [ ! $? -eq 0 ]; then
+      echo -e "${WHITE}#######################"
+      echo -e "${RED}Push Failed"
+      echo -e "${WHITE}"
+      return 1 # Failed
+    fi
+  fi
+
+
   echo -e "${WHITE}#######################"
   echo -e "${GREEN}Push Successfully"
   echo -e "${WHITE}"
@@ -5415,7 +5418,7 @@ function pullr {
   fi
 
   head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
-  if [ "$?" -gt 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
+  if [[ "$?" -gt 0 ]]; then #$(is_git_repo $PWD) -eq 1 ]; then
     echo -e "${RED}Not a Git Repo $(pwd)"
     echo -e "${WHITE}"
     return 1
@@ -5430,7 +5433,7 @@ function pullr {
 
   if [ -n "$(git status --porcelain)" ]; then
     git push --dry-run >/dev/null 2>&1
-    if [ $? -eq 0 ]; then
+    if [[ ! $? -eq 0 ]]; then
       echo -e "${YELLOW}Pushing Uncommited Changes First"
       echo -e "${WHITE}"
       pushr
@@ -5574,8 +5577,19 @@ function pulln {
       return 1
     else
 
+
+      if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then   
+          git push origin HEAD:develop
+      else
+          git push origin HEAD:main
+          #git checkout main
+      fi
+
+      git add --all >/dev/null 2>&1
+      git commit -m "*$@*" >/dev/null 2>&1
+
       git push --dry-run >/dev/null 2>&1
-      if [ ! $? -eq 0 ]; then
+      if [[ $? -eq 0 ]]; then
           # git pull --recurse-submodules
           # git submodule foreach --recursive "git checkout main && git push && git pull origin main" 2> /dev/null
           # #git submodule foreach --recursive "git add --all && git commit -m "*$@*" &&  git push && git checkout main && git push && git pull origin main" #2> /dev/null
